# -*- coding: utf-8 -*-
"""WebScrBBC.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1b7CDaoA65mI1sYxA7sooHctQ-Y3-W6e1
"""

pip install beautifulsoup4

pip install requests

#Importer les packages
import requests
from bs4 import BeautifulSoup 
import pandas as pd

#Saisir l'URL
url="http://feeds.bbci.co.uk/news/rss.xml"

#Importer le code de la page
reponse=requests.get(url)
soup=BeautifulSoup(reponse.text,"html.parser")
soup

items=soup.findAll('item')
item=items[0]
item.title.text

news_items=[]

for i in items:
  news_i={}
  news_i['title']=i.title.text
  news_i['description']=i.description.text
  news_i['pubdate']=i.pubdate.text
  news_items.append(news_i)

news_items

#Convertir la liste en base de Donnees
df=pd.DataFrame(news_items,columns=['title','description','pubdate'])

df.tail()

#generer le fichier csv
df.to_csv('Web_ScrapBBC.csv',index=False,encoding='utf-8')